name = "price-service"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 開發環境配置
[dev]
port = 8100
local = true

# 正式環境變數
[vars]
CACHE_TTL = "10"         # 快取時效預設5分鐘
MAX_BATCH_SIZE = "50"     # 批次處理最大數量

# 測試環境變數
[env.staging]
name = "price-service-staging"
vars = { CACHE_TTL = "10" }  # 測試環境快取時效縮短

# 正式環境
[env.production]
name = "price-service-prod"
vars = { CACHE_TTL = "10" }

# 資源限制配置
[limits]
cpu_ms = 10  # 每請求CPU時間限制
memory_mb = 128  # 記憶體限制

# 相容性標記
compatibility_flags = [
  "nodejs_compat",
  "durable_object_alarms"
] 