name = "price-service"
main = "./src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

# 開發環境配置
[dev]
port = 8100

# wrangler.toml
[observability.logs]
enabled = true

# 基礎配置
