name = "price-service"
main = "../../dist/workers/price-service/src/index.js"
compatibility_date = "2025-01-24"
compatibility_flags = ["nodejs_compat"]

# 開發環境配置
[dev]
port = 8100

# wrangler.toml
[observability.logs]
enabled = true

# 基礎配置
