name = "price-service"
main = "./src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

# 開發環境配置
[dev]
port = 8100

# wrangler.toml
[observability.logs]
enabled = true

# 基礎配置
[vars]
TWELVE_DATA_API_URL = "https://api.twelvedata.com"
CACHE_TTL = "5"
MAX_BATCH_SIZE = "5"