// Generated by Wrangler by running `wrangler types`

interface Env {
	PRICE_SERVICE: Fetcher;
	REGIONAL_DO: DurableObjectNamespace<import("./src/index").RegionalDO>;
}

declare global {
	interface CacheStorage {
		default: Cache;
	}
}

export {};
