// Generated by Wrangler by running `wrangler types`

export interface Env {
	CACHE_TTL: "10" | "3";
	MAX_BATCH_SIZE: "50" | "10";
	PRICE_SERVICE_URL: "https://price-service.a84012807.workers.dev" | "http://localhost:8100";
	NODE_ENV: "production" | "development";
	PRICE_SERVICE: Fetcher;
}
