name = "regional"
main = "./src/index.ts"
compatibility_date = "2024-04-03"

# Service bindings 配置
[[services]]
binding = "PRICE_SERVICE"  # 這是在程式中使用的名稱
service = "price-service"  # 這必須與 price-service worker 的 name 一致

# wrangler.toml
[observability.logs]
enabled = true


# 基礎配置（會被特定環境覆蓋）

# 本地開發配置
[dev]
port = 8000

# 使用 .dev.vars 文件來設置本地開發環境變數